### ISSUE TITLE
不刷新页面的方式好像还是有问题的。

### ISSUE THREAD

**Issue by ajiho** [leon-kfd/OnlineCodeEditor#2]
看了你知乎的文章中有提到说，通过简单的改写html/css/js实现不刷新页面更新页面效果，假如我在js编辑部分定义了一个常量，
const test = 'php是世界上最好的语言'；

防抖过后触发，控制台页面会一直报错。单纯的替换脚本js是不会被清除的。

还可以再优化一下

**Comment by ajiho** [comment]
在js部分编辑这段代码页面会直接消失
```
parent.document.body.innerHTML = ''
```

**Comment by leon-kfd** [comment]
已将js代码方式改成iife方式闭包执行，第一个问题解决。另外拦截替换了parent.document防止直接操作父窗口。

https://github.com/leon-kfd/OnlineCodeEditor/commit/379a582a685c3dc07af7173d435b8df7c74aef2a
